### ISSUE TITLE
[ES] Definir o tema do projeto

### ISSUE THREAD

**Issue by viniciusgiles** [gilesv/Sonegators#1]

**Comment by viniciusgiles** [comment]
Pesquisar fontes interessantes de dados abertos e postar aqui

**Comment by mvhb** [comment]
https://dadosabertos.camara.leg.br/swagger/api.html

**Comment by aacgn** [comment]
Dados Abertos da Câmera dos Deputados: Vamos pegar os votos dos deputados em relação a projetos específicos.

**Comment by mvhb** [comment]
https://idg.receita.fazenda.gov.br/dados
Ideia: um portal que mostrasse, com grande apelo visual, o quanto de dinheiro foi tirado do nosso bolso e o quanto realmente foi investido em coisa que preste

**Comment by mvhb** [comment]
http://dadosabertos.bcb.gov.br/

**Comment by mvhb** [comment]
https://dadosabertos.camara.leg.br/

**Comment by eduardosm7** [comment]
https://twitter.com/

**Comment by mvhb** [comment]
academia da cidade - http://dados.recife.pe.gov.br/dataset/academias-da-cidade/resource/874379d1-470f-40bb-a469-fe0228c62d09

**Comment by mvhb** [comment]
hoteis recife - http://dados.recife.pe.gov.br/dataset/hoteis/resource/0d8fb090-2863-4d51-9b21-baae4bae5a11

**Comment by eduardosm7** [comment]
http://datahub.io/

**Comment by aacgn** [comment]
http://www.fnde.gov.br/dadosabertos/

**Comment by aacgn** [comment]
https://idg.receita.fazenda.gov.br/dados/receitadata/arrecadacao/relatorios-do-resultado-da-arrecadacao

**Comment by viniciusgiles** [comment]
Receita Recife: http://dados.recife.pe.gov.br/dataset/receitas
Despesas orçamentárias Recife: http://dados.recife.pe.gov.br/dataset/despesas-orcamentarias

**Comment by viniciusgiles** [comment]
Demandas dos cidadãos Recife:http://dados.recife.pe.gov.br/dataset/demandas-dos-cidadaos-e-servicos-dados-vivos-recife

**Comment by viniciusgiles** [comment]
http://dados.recife.pe.gov.br/dataset/bares-e-restaurantes

Aplicação web que recomenda novos ambientes (bares e restaurantes) baseados em gostos pessoais do usuário como tipo de vinho, música, especialidade, comida, local e ambiente, e compartilhará com seus contatos via Facebook e Twitter. Será possível avaliar, recomendar e adicionar informações ao app.

Where I Go?
