### ISSUE TITLE
[ES] Iteração [0-2] (25/09)

### ISSUE THREAD

**Issue by aacgn** [gilesv/Sonegators#10]
[0-2]: Mockups e HU.

**Comment by aacgn** [comment]
USERS:

1-CONSUMIDOR
2-PRESTADOR DE SERVIÇOS


1-MARCOS
2-VINICIUS FOOD

H1 - CONSUMIDOR

1-Como um consumidor, marcos precisa ver facilmente novos estabelecimentos.
2-Como um consumidor, marcos precisa ver facilmente indicações.
3-Como um consumidor, marcos precisa ter facil acesso a ferramenta de busca.
4-Como um consumidor, marcos precisa adicionar informações pessoais a sua conta.
5-Como um consumidor, marcos pode facilmente indicar locais a seus amigos.
6-Como um consumidor, marcos pode facilmente cadastrar informações de estabelicimentos.
7-Como um consumidor, marcos pode avaliar os locais, deixando um feedback privado para os estabelecimentos.
8-Como um consumidor, marcos pode facilmente adicionar joinhas, que serão publicos, ao estabelecimento.
9-Como um consumidor, marcos pode seguir promoções/eventos de estabelecimentos.

H2 - PRESTADOR DE SERVIÇOS

1-Como um prestador, vinicius precisa ver facilmente os feedbacks associados ao seu estabelecimento.
2-Como um prestador, vinicius precisa facilmente cadastrar informações de seu estabelecimento.
3-Como um prestador, vinicius precisa ver quantas indicações foram feitas em seu estabelecimento.
4-Como um prestador, vinicius precisa facilmente validar, editando ou removendo, as informações cadastradas por usuários.
5-Como um prestador, vinicius pode facilmente adicionar promoções/eventos ao seu estabelecimento.

**Comment by viniciusgiles** [comment]
![whereigo_lo-fi_mockup](https://user-images.githubusercontent.com/18203276/30778139-0ebbb2b4-a0a4-11e7-8f11-93eda8fbd0b7.png)
