### ISSUE TITLE
[PGP] Elaborar perguntas p/ aula de 15/09

### ISSUE THREAD

**Issue by eduardosm7** [gilesv/Sonegators#17]

**Comment by eduardosm7** [comment]
Qual a principal preocupação que se deve ter no estágio de Normalização no processo de evolução de um grupo?
R - Tentar sempre manter a visão crítica da equipe.

**Comment by mvhb** [comment]
Qual a importância da escolha da quantidade de membros envolvidos no projeto? Adicionar mais membros ajuda na produtividade do projeto?
R- É de extrema importância, cada atividade depende, mas geralmente grupos menores são mais produtivas, quanto a adicionar mais pessoas, geralmente é o oposto da produtividade, pois se faz necessário adicionar esse pessoa no contexto do projeto e isso leva tempo.

**Comment by mvhb** [comment]
A diversidade ajuda na obtenção de resultados melhores? 
R- Sim, por isso é buscado ter vários perfis (pessoais) diferentes num mesmo projeto, como por exemplo Plant, Resource Investigator, Monitor-Evaluator, Team Worker e Completer-finisher.

**Comment by eduardosm7** [comment]
Em que pontos os gerentes de projeto costumam falhar quando se trata da comunicação com o time?
R - Na grande maioria das vezes, a comunicação de objetivos e prioridades não são feitas de maneira adequada, fazendo com que a equipe tome rumos diferentes de que os esperados.
