### ISSUE TITLE
[PGP] Elaborar perguntas p/ aula de (22/09)

### ISSUE THREAD

**Issue by mvhb** [gilesv/Sonegators#18]

**Comment by eduardosm7** [comment]
Quais as principais características um Gerente de Projeto tem que possuir?
R - Conhecimento, Desempenho, Pessoal

**Comment by mvhb** [comment]
Cite pelo menos três habilidades de um bom gerente de projeto

**Comment by mvhb** [comment]
Como garantir uma boa comunicação em um projeto?

**Comment by mvhb** [comment]
Qual as diferenças entre os três tipos de estrutura matricial?
