### ISSUE TITLE
[BD] 1ª ENTREGA: definição do Minimundo e modelagem Entidade-Relacionamento

### ISSUE THREAD

**Issue by viniciusgiles** [gilesv/Sonegators#2]
Descrição do mundo real a ser modelado pela aplicação; Descrição dos objetivos da aplicação;
Descrição das perguntas/ relatórios importantes que deverão ser implementados pela aplicação;
Descrição informal dos dados (entidades, relacionamentos, atributos, etc.) observados.
O minimundo deve conter: mínimo de 5 entidades, uma delas fraca; Relacionamentos binários e ternários;
Auto-relacionamento; Entidade associativa; Especialização; Atributos simples, compostos, multivalorados;
Construir o diagrama ER do projeto utilizando Ferramenta CASE

**Comment by aacgn** [comment]
O minimundo deve conter: 
- [x] mínimo de 5 entidades
1. Empregado
2. Chefe de cozinha
3. Cozinheiro
4. Manobrista
5. Prato
6. Garçom
7. Criança
8. Nota fiscal
9. Mesa
10. Cliente
11. Conta
12. Recepcionista
13. Veículo
14. Fornecedor
15. Produto

- [x] Entidade fraca
1. Criança

- [x] Relacionamentos binários
1. Manobra (entre Manobrista e Veículo)
2. Emite (entre Paga e Nota fiscal)
3. Possui (Cliente e Criança)
4. Tem (Cliente e Veículo)
5. Fica (Mesa e Cliente)

- [x] Relacionamento ternário
1. Pede (Cliente, Garçom e Prato)
2. Leva para (Garçom, Prato e Mesa)
3. Fornece (Fornecedor, Produto e Chefe de cozinha)
4. Guia (Recepcionista, Cliente e Mesa)

- [x] Auto-relacionamento
1. Cozinha para (Cozinheiro)

- [x] Entidade associativa
1. Paga

- [x] Especialização
Empregado (Manobrista, cozinheiro, chefe de cozinha, recepcionista, garçom)
- [x] Atributos simples
- [x] Atributo composto
1. Endereço (Empregado)
2. Placa (Veículo)

- [x] Atributo multivalorado
1. Telefone (Empregado)

**Comment by aacgn** [comment]
![modelo er](https://user-images.githubusercontent.com/20008547/29998461-ea709f80-9001-11e7-932d-8166d97f2f25.jpg)

**Comment by viniciusgiles** [comment]
![fgdfg](https://user-images.githubusercontent.com/18203276/30038580-a5819a5e-919c-11e7-830d-6fc42687a693.jpg)
versão final

**Comment by aacgn** [comment]
![modelo](https://user-images.githubusercontent.com/20008547/30039296-46bad4be-91a5-11e7-8fda-87f304c68780.jpg)

**Comment by viniciusgiles** [comment]
**Comentários do professor**
- Minimundo: Sim
- Perguntas/relatórios: Não
- Modelo ER:
  - 5 entidades (1 fraca): Sim
  - Relacionamento binário: Sim
  - Relacionamento ternário: Sim
  - Auto-relacionamento: Sim
  - Entidade associativa: Sim
  - Especialização: Sim
  - Atributo simples:Sim
  - Atributo composto: Sim
  - Atributo multivalorado: Sim
  - Fez uso de ferramenta CASE: Sim
- Comentários: A equipe não preparou uma lista de perguntas/relatórios que o sistema precisa responder/gerar. Seria mais preciso dizer que é identificado unicamente por CPF ou RG. Eu não modelaria a placa de um carro separando letras de números, pois acredito ser uma informação atômica. Não ficou claro para mim que Criança é um dependente de Cliente. Se a nota fiscal for gerada para todo pagamento, o que deveria ser o caso, o relacionamento com nota fiscal deveria ser ternário e não uma entidade associativa (P1). CNH é uma chave candidata para manobrista. Não entendi o porquê de um manobrista só poder manobrar no máximo 1 carro. Do lado do veículo, talvez pudesse ser um relacionamento total (no mínimo 1), pois o sistema só deve querer armazenar informação do carro se o mesmo for ser manobrado. É possível que total a pagar seja um atributo derivado. Não faz sentido o cliente só poder pagar no máximo 1 conta. Se o mesmo cliente vai várias vezes no restaurante, ele vai no final estar relacionado a várias contas. Conta é uma entidade sem atributo identificador (P3). Talvez o mesmo veículo possa estar associado a clientes diferentes. O mesmo veículo pode ser compartilhado por um casal. Suponha que em um momento só vai uma pessoa do casal e em outro vai a outra. Se em ambos os casos o carro for ser manobrado, você teria o mesmo veículo manobrado por várias pessoas. Faltam informações em alguns relacionamentos (P4). Por exemplo, o cliente pede pratos. Se o cliente for duas vezes no restaurante, como saber quais pratos foram pedidos na 1a vez e quais na 2a vez? Como o sistema irá gerar a conta a ser paga? Portanto, acho que o pedido precisa ter um tempo. O guia/fica para uma mesa também. Há outras maneiras de resolver esta situação, mas do jeito que o modelo está não é possível saber o que deve ser pago. As cardinalidades do diagrama (como um todo) precisam ser revistas (P5 e P6). O mesmo cliente pode ficar em momentos distintos em mesas distintas, não? Assim sendo, como o cliente pode estar associado no máximo a uma mesa? Se o prato do cliente pode ser feito por vários cozinheiros, por que o prato que o cozinho vai fazer para outro cozinheiro é feito por somente um cozinheiro?

**Comment by mvhb** [comment]
Modelo atualizado já está no drive.

**Comment by jackweb1970** [comment]
Estou procurando ferramenta para construir modelagem conforme as imagens acima, você pode me informar?
