### ISSUE TITLE
[ES] Iteração [1-1] (02/10)

### ISSUE THREAD

**Issue by mvhb** [gilesv/Sonegators#20]

**Comment by aacgn** [comment]
1. Fazer curso de Rails do Code Academy: https://www.codecademy.com/learn/learn-rails
2. Fazer curso de Autenticação em Rails do Code Academy: https://www.codecademy.com/learn/rails-auth
3. Planejar e desenvolver banco de dados
4. Importar dados "csv" de bares e restaurantes disponibilizados pela Prefeitura do Recife (http://dados.recife.pe.gov.br/dataset/bares-e-restaurantes)
5. Incorporar csv ao banco de dados
6. Fazer tela de login e cadastro
7. Fazer sistema de autenticação de usuário/prestador
8. Assistir e entender tutorial do API do Google Maps on Rails: https://www.youtube.com/watch?v=oi3yxYs8Y4Q
9. Fazer sistema de busca a partir dos dados encontrados no banco de dados e exibi-los através da API do Google Maps

**Comment by viniciusgiles** [comment]
10. Criar identidade visual da aplicação (logotipo, esquema de cores, etc.)

**Comment by aacgn** [comment]
ME MAMA MARCOS: https://www.youtube.com/watch?v=OTSpvEuqISw

**Comment by aacgn** [comment]
http://guides.rubyonrails.org/v3.2.8/getting_started.html

**Comment by viniciusgiles** [comment]
Estou fazendo o curso do codecademy de Rails, é massa

**Comment by aacgn** [comment]
http://flatfull.com/themes/note/mail.html
