### ISSUE TITLE
[SGE] 1º STATUS REPORT (05/10)

### ISSUE THREAD

**Issue by mvhb** [gilesv/Sonegators#22]

**Comment by viniciusgiles** [comment]
Modo não-documentado: liga para a Sinfra requisitando uma equipe de infraestrutura (demora mt)

**Comment by viniciusgiles** [comment]
**Melhorias para 1o status report**
Pontos de melhorias: aprofundamento do problema e, consequentemente, da solução e proposta de valor; deixar mais claro o valor associado ao planejamento da implantação.
No proxímo status não esquecer de apresentar como o processo definido está sendo seguido.

**Comment by viniciusgiles** [comment]
**Contexto**
- A infraestrutura da UFPE está sempre em reforma e ampliação.

**Problema (geral)**
- Maioria das obras está atrasada, com orçamento estourado e com fiscalização insuficiente. Manutenções demoradas devido a falta de recursos e mão-de-obra.

**Escopo**
- Processo de requisição de manutenções de infraestrutura, sendo elas corriqueiras ou planejadas.

**Contexto do escopo**
- Manutenções prediais são frequentemente requisitadas na universidade
- Atualmente não existe um meio de acompanhamento das requisições

**Problema (escopo)**
- O processo de análise e execução das requisições de manutenção é demorado e ineficiente
