### ISSUE TITLE
[PGP] 2a. entrega - 1o. Status Report (06/10)

### ISSUE THREAD

**Issue by mvhb** [gilesv/Sonegators#23]
Plano de Projeto Preliminar (declaração de escopo preliminar, plano de recursos humanos/stakeholders, plano de comunicação), diário de atividades do aluno e avaliação 360o. dos membros das equipes.

**Comment by mvhb** [comment]
![image](https://user-images.githubusercontent.com/19848903/31278153-4b87043e-aa7a-11e7-8bcf-e4032a9343e4.png)

**Comment by aacgn** [comment]
Elaborado!
