### ISSUE TITLE
[BD] Entrega do projeto 2 (08/10)

### ISSUE THREAD

**Issue by mvhb** [gilesv/Sonegators#24]

**Comment by mvhb** [comment]
*Entregar até domingo

**Comment by eduardosm7** [comment]
Consertar o diagrama da entrega passada com os comentários dele.

**Comment by mvhb** [comment]
2a. Entrega: esquema relacional normalizado: o mapeamento do diagrama ER para o modelo relacional, com as relações normalizadas.

**Comment by mvhb** [comment]
![versao corrigida](https://user-images.githubusercontent.com/19848903/31311960-4740d1ce-ab8e-11e7-95a9-9a5e3608cb0b.jpg)

**Comment by mvhb** [comment]
![versao corrigida](https://user-images.githubusercontent.com/19848903/31312683-6b624ddc-aba0-11e7-8ec4-0658784c4146.jpg)
