### ISSUE TITLE
[SGE] Entrevista com o cliente (28/09)

### ISSUE THREAD

**Issue by mvhb** [gilesv/Sonegators#26]

**Comment by eduardosm7** [comment]
Qual o principal  problema do processo que se encontram as falhas que causam o estouro de orçamento e do prazo, para podermos definir melhor nosso escopo. (ex. se é no contrato, na fiscalização)

**Comment by mvhb** [comment]
Falar com o cliente para reduzir o escopo para obras de construção, sem levar em consideração manutenções, uma vez que os principais problemas se encontram em novas obras

**Comment by viniciusgiles** [comment]
Entender o processo inicial de todo projeto de obra: como são geradas as licitações e contratos que contém todo o planejamento da obra

**Comment by viniciusgiles** [comment]
[Pergunta da primeira entrevista] onde é possível encontrar as informações das obras?

**Comment by mvhb** [comment]
Os registros das obras são feitos manualmente ou existe algum processo eletrônico?

**Comment by mvhb** [comment]
Posso desistir?
