### ISSUE TITLE
[GPN] 2ª ENTREGA (22/09): Entrevista com o cliente

### ISSUE THREAD

**Issue by viniciusgiles** [gilesv/Sonegators#7]
Fazer perguntas e escrever respostas do cliente nessa discussão.
**Estabelecer perfil do Cliente ou Usuário** 

- Nome: 
- Empresa: 
- Indústria: 
- Cargo: 
- Quais são as suas principais responsabilidades? 
- Que saídas (produtos/serviços) que você produz? 
- Para quem? 
- Como o sucesso é medido? 
- Que problemas interferem no seu sucesso? 
- Quais, se houver, as situações que tornam seu trabalho mais fácil ou mais difícil?

 
**Avaliação do Problema** 

- Para quais problemas você acha que faltam boas soluções? 
- Quais são eles? (Dica: continue perguntando “Algo mais?”) 
- Para cada problema listado, você deve perguntar: 

1. • Por que o problema existe? 
2. • Como você o resolve agora? 
3. • Como você gostaria de resolvê-lo? 

**Entendendo o ambiente do usuário** 

- Quem são os usuários? 
- Qual é a sua formação? 
- Qual é a sua base no uso de computadores? 
- São usuários experientes com este tipo de aplicação? 
- Que plataformas estão em uso? 
- Quais são seus planos para plataformas futuras? 
- Quais são as suas expectativas com relação à usabilidade para este tipo de produto? 
- Quais são suas expectativas para o tempo de treinamento? 
- Que tipos de ajuda ao usuário você precisa? 

**Recaptule o entendimento**
Você me disse: 
(Liste e leia os problemas descritos usando as suas próprias palavras) 
Suposições do Analista sobre os Problemas do Cliente 
 (Validar ou invalidar suposições feitas pelo analista) 
Para cada problema, pergunte: 
• Este é um problema real? 
• Quais são as razões para a existência deste problema? 
• Como você atualmente resolve este problema? 
• Como você gostaria de resolver este problema? 
• Como você classificaria a solução deste problema, em comparação aos outros que você mencionou? A solução é adequada?
Avalie a solução que você tem em mente perguntando ao cliente qual a opinião dele
Ex. E se nós tivéssemos esta característica no software para solucionar este problema que você apresentou?

**Perguntas que nós definimos**

1. Que tipo de obras serão avaliadas? (construção, reformas, etc…)
2. Como é realizado o planejamento das obras?
3. Como são definidos o prazo?
4. Como é definida a empresa encarregada da obra?
5. Como é realizada a fiscalização das obras? Quem é o responsável por fiscalizar?
6. Como são tratados os possíveis imprevistos nas obras?
7. Onde é possível encontrar dados e informações das obras?
8. Como é definido o valor disponível para a obra?
9. Qual foi o período em que ocorreu a maior incidência desse problema de atraso nas obras?
10. Que tipo de obra geralmente dá mais problema em relação ao planejamento e a orçamento?
11. O que acontece com a empresa contratada caso ela não cumpra com suas obrigações (orçamento, prazo, etc)?
12. Com várias obras em andamento paralelamente, existe alguma prioridade?

**Comment by mvhb** [comment]
*Entrega dia 22/09
