### ISSUE TITLE
[PGP] Elaborar perguntas p/ aula de 01/09

### ISSUE THREAD

**Issue by eduardosm7** [gilesv/Sonegators#8]
Podem ser perguntas com respostas ou dúvidas/pontos a discutir com toda a turma

**Comment by mvhb** [comment]
Qual a diferença principal entre projetos e operações?
R - Projetos são únicos e temporários, enquanto operações são contínuas e repetitivas

**Comment by eduardosm7** [comment]
Ponto: É possível afirmar que toda operação veio de um planejamento anterior a ela?

**Comment by mvhb** [comment]
Quais são as ferramentas e técnicas que podem ser utilizadas para o desenvolvimento de um Project Charter (termo de abertura)?
R- Métodos de seleção de projetos, sistemas de informação de gerenciamento de projetos e opinião especializada

**Comment by eduardosm7** [comment]
Qual o conteúdo básico que está presente no Project Charter?
R - Justificativa do projeto (referência ao contrato, se houver); 
      Entrega(s) que deve(m) ser gerada(s) pelo projeto;
      Identificação do GP e sua autoridade e responsabilidade no projeto; 
      Premissas; 
      Restrições.
