### ISSUE TITLE
[PGP] 1ª ENTREGA: Termo de Abertura do Projeto

### ISSUE THREAD

**Issue by viniciusgiles** [gilesv/Sonegators#9]
Estamos próximos da entrega do termo de abertura (15/09). Lembrem-se de que existe uma página no site da disciplina com templates dos artefatos a serem entregues por vocês. Procurem seguir os modelos e atentem-se para o fato de que os projetos de PGP, SGE e GPN (Aos que estão cursando as três disciplinas) são projetos integrados, então seria interessante a inserção de conteúdo de outras disciplinas nas entregas do projeto de vocês (e vice-versa).

**Comment by mvhb** [comment]
1a. entrega - Termo de abertura do Projeto (Objetivos do Projeto, equipe/stakeholders e marcos principais), diário de atividades do aluno e avaliação 360o. dos membros das equipes.

**Comment by mvhb** [comment]
Crie um doc no drive @gilesv @aacgn @eduardosm7
